<?php
//配置文件
use app\index\model\sys ;
$sys=sys::all();
$web_info=$sys[0]['info'];
return [
    'sys_name'  =>  $web_info['sys_name'],//系统名称
    'web_name'  =>  preg_replace('# #', '', $web_info['company_name']),//公司名称
    'web_tel'   =>  preg_replace('# #', '', $web_info['company_tel']),//公司电话
    'web_add'   =>  preg_replace('# #', '', $web_info['company_add']),//公司地址
    'web_ver'   =>  preg_replace('# #', '', file_get_contents($_SERVER['DOCUMENT_ROOT']."/application/index/ver")),//程序版本
    //功能授权-页面类['MAIN函数名'=>'自定义名称']
    'root_info' => [
        'purchase'=>'purchase_add',
        'opurchase'=>'opurchase_add',
        'opurchase_form'=>'opurchase_form',
        'orpurchase'=>'rpurchase_add',
        'rpurchase_form'=>'rpurchase_form',
        'purchase_form'=>'purchase_form',
        'purchase_bill'=>'purchase_form',
        'sale'=>'sale_add',
        'sale_form'=>'sale_form',
        'sale_bill'=>'sale_form',
        'repurchase'=>'repurchase_add',
        'repurchase_form'=>'repurchase_form',
        'repurchase_bill'=>'repurchase_form',
        'resale'=>'resale_add',
        'resale_form'=>'resale_form',
        'resale_bill'=>'resale_form',
        'cashier'=>'cashier_add',
        'cashier_form'=>'cashier_form',
        'recashier'=>'recashier_add',
        'recashier_form'=>'recashier_form',
        'allocation'=>'allocation_add',
        'allocation_form'=>'allocation_form',
        'otpurchase'=>'otpurchase_add',
        'otpurchase_form'=>'otpurchase_form',
        'otsale'=>'otsale_add',
        'otsale_form'=>'otsale_form',
        'gather'=>'gather_add',
        'gather_form'=>'gather_form',
        'payment'=>'payment_add',
        'payment_form'=>'payment_form',
        'otgather'=>'otgather_add',
        'otgather_form'=>'otgather_form',
        'otpayment'=>'otpayment_add',
        'otpayment_form'=>'otpayment_form',
        'room_check'=>'room_add',
        'room_warning'=>'room_add',
        'room'=>'room_add',
        'customer'=>'basics_form',
        'supplier'=>'basics_form',
        'goods'=>'basics_form',
        'warehouse'=>'basics_form',
        'account'=>'basics_form',
        'goodsclass'=>'auxiliary_form',
        'unit'=>'auxiliary_form',
        'brand'=>'auxiliary_form',
        'code'=>'auxiliary_form',
        'attribute'=>'auxiliary_form',
        'often'=>'auxiliary_form',
        'sys'=>'senior_form',
        'user'=>'senior_form',
        'db_backup'=>'senior_form',
        'auth'=>'senior_form',
        'log'=>'senior_form',
        'root'=>'senior_form',
        'arrears_form'=>'data_form',
        'profit_form'=>'data_form',
        'itemorder'=>'itemorder_add',
        'itemorder_form'=>'itemorder_form',
        'itemorder_bill'=>'itemorder_form',
        'exchange'=>'exchange_add',
        'exchange_form'=>'exchange_form',
        'eft'=>'eft_add',
        'eft_form'=>'eft_form',
		'ape_goods_form'=>'data_form',
    ]
];
